FOGL-2271 - Run Async mode python plugins using the C++ south service
foglamp/foglamp-south-sinusoid pull request #22
Opened 2019-01-28 07:05 UTC by amarendra-dianomic

2019-01-28 10:27 UTC, AmandeepArora commented on python/foglamp/plugins/south/sinusoid/sinusoid.py
> +            _LOGGER.info("sinusoid: returning reading via ingest.ingest_callback, %s", handle['assetName']['value'])
May be change these INFO logs to DEBUG logs? or change logger level above to WARN.

2019-01-28 10:27 UTC, AmandeepArora commented on python/foglamp/plugins/south/sinusoid/sinusoid.py
> +        'description': 'Sinusoid Plugin',
May be add "async" in the middle to differentiate it clearly from poll version.

2019-01-28 14:58 UTC, MarkRiddoch reviewed
Other than test purposes is there any advantage to having an async sinusoid?

2019-01-28 15:11 UTC, praveen-garg requested changes

2019-01-28 15:11 UTC, praveen-garg commented on test/test_sinusoid.py
>      # Evaluates if the plugin has all the required methods
revert this file chnages

2019-01-28 15:11 UTC, praveen-garg commented on python/foglamp/plugins/south/sinusoid/sinusoid.py
> +                handle['dataPointsPerSec']['value'] = '1'
South C server add `readingsPerSec` to AdvanceConfig; what should be the valid config item in this case?

2019-01-28 15:11 UTC, praveen-garg commented on python/foglamp/plugins/south/sinusoid/sinusoid.py
> +c_ingest_ref = None
Can we keep these 3 variables in handle or some BasePlugin Object? so that we don't need to make these global.

2019-01-28 15:26 UTC, praveen-garg commented
> Other than test purposes is there any advantage to having an async sinusoid?

@MarkRiddoch  we will just keep this as a test (experimental) branch (may be protect with name async_backup_south_c) and get rid of this, when we are done with few versions of releases with FOGL-2312 success.

2019-01-30 16:29 UTC, praveen-garg approved these changes

2019-01-31 10:17 UTC, praveen-garg requested changes
We should change the plugin version to 2.0 and if  plugin **upgrade** happens python south server should check plugin mode AND version:
if async 2.0  then:
* change scheduled process to south_c 
* and disable and enable the schedule. (restart the service)
* AND log the actions so that it can be loaded via south_c server without any manual modification

2019-01-31 12:02 UTC, praveen-garg commented
This will be merged into `async_backup_south_c`

2019-01-31 12:15 UTC, praveen-garg commented on python/foglamp/plugins/south/sinusoid/sinusoid.py
> +        'description': 'Sinusoid Plugin',
chnaged in plugin_info hook

2019-01-31 12:24 UTC, praveen-garg approved these changes

2019-02-01 10:34 UTC, merged